name: update-test-repo
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REMOTE_MERGE_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Git-version
        run: git version

      - name: Git-remote-add
        run: git remote add testrepo https://github.com/mgguild/test-gamevault-frontend.git

      - name: Git-fetch-all
        run: git fetch --all

      - name: Git-checkout-test
        run: git checkout -b main testrepo/main

      - name: Git-merge
        run: git merge origin/develop

      - name: Git-push
        run: git push testrepo main
